# Generated by Django 5.2.4 on 2025-08-06 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_type', models.CharField(choices=[('wifi', 'Wi-Fi'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('parking', 'Parking'), ('ac', 'Air Conditioning'), ('laundry', 'Laundry Service'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('spa', 'Spa'), ('pet_friendly', 'Pet Friendly'), ('kids_play_area', 'Kids Play Area'), ('game_room', 'Game Room'), ('meeting_room', 'Meeting Room')], default='parking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('hotel_type', models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('resort', 'Resort'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('hostel', 'Hostel'), ('suit', 'Suit')], default='hotel', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.destination')),
                ('facilities', models.ManyToManyField(related_name='facility', to='hotel.facility')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_managers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('star_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('king', 'King'), ('deluxe', 'Deluxe')], max_length=50)),
                ('room_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('person', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('amenities', models.CharField(choices=[('ac', 'Air Conditioning'), ('wifi', 'Free WiFi'), ('minibar', 'Minibar'), ('tv', 'Smart TV with Streaming'), ('room_service', 'Room Service Available'), ('balcony', 'Private Balcony'), ('soundproof', 'Soundproof Windows'), ('safe', 'In-Room Safe'), ('desk', 'Desk & Workstation'), ('coffee', 'Coffee/Tea Maker')], max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
